booking/urls.py
from django.urls import path
from . import views


app_name = 'booking'

urlpatterns = [
    path('', views.table_booking, name='table_booking'),
    path('manage_booking/',
         views.BookingsList.as_view(), name='manage_booking'),
    path('edit_booking/<booking_id>/', views.edit_booking,
         name='edit_booking'),
    path('delete_booking/<booking_id>/', views.delete_booking,
         name='delete_booking')
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu_list, name='menu_list'),
]

restaurant_website/urls.py
from django.contrib import admin
from django.urls import path, include
from restaurant.views import IndexPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPage.as_view(), name='index'),
    path('menu_list/', include('menu.urls', namespace='menu_list')),
    path('table_booking/', include('booking.urls', namespace='table_booking')),
    path('accounts/', include('allauth.urls')),
]

admin.site.site_header = 'Happy Leeks AdminPanel'

booking/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


TIME_CHOICES = (
    ('08:00 AM', '08:00 AM'),
    ('09:00 AM', '09:00 AM'),
    ('10:00 AM', '10:00 AM'),
    ('11:00 AM', '11:00 AM'),
    ('12:00 PM', '12:00 PM'),
    ('13:00 PM', '13:00 PM'),
    ('14:00 PM', '14:00 PM'),
    ('15:00 PM', '15:00 PM'),
)


class Booking(models.Model):

    """
    Creates model for table bookings
    """

    name = models.CharField(max_length=30)
    phone = models.IntegerField()
    number_of_guests = models.IntegerField(default=1,
                                           validators=[MaxValueValidator(4),
                                                       MinValueValidator(1)])
    date = models.DateField()
    time = models.CharField(
        max_length=8, choices=TIME_CHOICES, default='08:00 AM',)

    def __str__(self):
        return self.name

menu/models.py
from django.db import models
from django.utils.text import slugify


class Menu(models.Model):
    """
    Creates the menu model
    """
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=400)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'menu item'
        verbose_name_plural = 'menuitems'

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Menu, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    Creates catgegories for menu items
    """
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

restaurant/models.py
from django.db import models

booking/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    """
    Table booking form
    """

    number_of_guests = forms.IntegerField(required=True,
                                          widget=forms.TextInput(
                                              attrs={
                                                  'pattern': '[1-4]+',
                                                  'title': 'Enter a number between 1 and 4.'
                                              }

                                          ))
    date = forms.DateField(input_formats=['%d/%m/%Y'],
                           widget=forms.DateInput(attrs={
                               'placeholder': 'dd/mm/yyyy'
                           }))

    name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'pattern': '[A-Za-z ]+', 'title': 'Enter characters only.'}))

    phone = forms.IntegerField(required=True,
                               widget=forms.TextInput(
                                   attrs={
                                       'placeholder': '0123456789',
                                       'pattern': '[0123456789]+',
                                       'title': 'Enter digits only.'
                                   }
                               )
                               )

    class Meta:
        model = Booking
        fields = '__all__'

booking/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic, View
from django.contrib import messages
from .forms import BookingForm
from .models import Booking


def table_booking(request):
    """
    Lets user create a booking
    """
    booking_form = BookingForm()

    if request.method == 'POST':
        booking_form = BookingForm(request.POST)
        if booking_form.is_valid():
            booking_form.instance.name = request.user
            booking_form.save()
            messages.success(request, 'Booking successful.')
            return redirect(reverse('booking:manage_booking'))
        else:
            messages.error(request, 'Booking unsuccessful. Please try again.')
    else:
        booking_form = BookingForm()

    context = {
        'form': booking_form
    }
    return render(request, '../templates/booking.html', context)


class BookingsList(generic.View):
    """
    Customer will be able to view their booking/s
    """
    model = Booking
    queryset = Booking.objects.all()
    template_name = 'manage_booking.html'
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            bookings = Booking.objects.filter(name=request.user)

            context = {
                'bookings': bookings,
            }

            return render(request, 'manage_booking.html', context)


def edit_booking(request, booking_id):
    """
    Lets user updated their booking
    """
    booking = get_object_or_404(Booking, id=booking_id)
    if request.method == 'POST':
        booking_form = BookingForm(request.POST, instance=booking)
        if booking_form.is_valid():
            booking_form.save()
            messages.success(request, 'Booking updated successfully.')
            return redirect('booking:manage_booking')
        else:
            messages.error(request, 'Update unsuccessful. Please try again.')

    booking_form = BookingForm(instance=booking)

    return render(request, 'edit_booking.html', {'form': booking_form})


def delete_booking(request, booking_id):
    """
    Lets user delete their booking
    """
    booking = get_object_or_404(Booking, id=booking_id)
    booking.delete()
    messages.success(request, 'Booking deleted successfully.')
    return redirect('booking:manage_booking')

menu/views.py
from django.shortcuts import render
from .models import Menu, Category


def menu_list(request):
    """
    Creates menu
    """
    menu_list = Menu.objects.all()
    categories = Category.objects.all()

    context = {
        'menu_list': menu_list,
        'categories': categories,
    }

    return render(request, '../templates/menu.html', context)

restaurant/views.py
from django.shortcuts import render
from django.views import generic, View


class IndexPage(View):
    """
    Customer will be able to view the landing page
    """

    def get(self, request, *args, **kwargs):
        return render(request, '../templates/index.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Happy Leeks. Vegan Cafe serving breakfast and lunch.">
    <meta name="keywords" content="food, cafe, vegan, breakfast, lunch, coffee, good vibes">
    <meta name="author" content="Sina Stiller">
    <title>{% block title %} Happy Leeks | Vegan Cafe 🌱 {% endblock %}</title>

    <!-- Facivon -->
    <link rel="apple-touch-icon" sizes="180x180"
        href="https://res.cloudinary.com/dwztcnhyh/image/upload/v1687965863/apple-touch-icon_u9o3df.png">
    <link rel="icon" type="image/png" sizes="32x32"
        href="https://res.cloudinary.com/dwztcnhyh/image/upload/v1687965864/favicon-32x32_xbbghh.png">
    <link rel="icon" type="image/png" sizes="16x16"
        href="https://res.cloudinary.com/dwztcnhyh/image/upload/v1687965864/favicon-16x16_nfykn3.png">

    <!-- Bootstrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column vh-100 main-bg">
    <header>
        <!-- Navigation bar-->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div id="navbar" class="container-fluid">

                <a class="navbar-brand mb-0 h1" href="{% url 'index' %}"> Happy Leeks <img
                        src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1687965864/favicon-32x32_xbbghh.png"
                        alt="logo"> </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item align-self-end">
                            <a class="nav-link active " aria-current="page" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item align-self-end">
                            <a class="nav-link" href="{% url 'menu:menu_list' %}">Menu</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item align-self-end">
                            <a class="nav-link" href="{% url 'booking:table_booking' %}">Book a Table</a>
                        </li>
                        {% endif %}
                        <li class="nav-item dropdown align-self-end">
                            {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Hello, {{ user }} !
                            </a>
                            {% else %}
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                My Account
                            </a>
                            {% endif %}
                            <ul class="dropdown-menu mb-2">
                                {% if user.is_authenticated %}
                                <li class="align-self-end"><a class="dropdown-item"
                                        href="{% url 'booking:manage_booking' %}">Manage Booking</a></li>
                                <li class="align-self-end"><a class="dropdown-item"
                                        href="{% url 'account_logout' %}">Logout</a></li>
                                {% else %}
                                <li class="align-self-end"><a class="dropdown-item"
                                        href="{% url 'account_signup' %}">Sign Up</a></li>
                                <li class="align-self-end"><a class="dropdown-item"
                                        href="{% url 'account_login' %}">Login</a></li>
                                {% endif %}

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissable fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </header>

    <main>
        {% block content %}

        {% endblock content %}
    </main>

    <footer class="footer">
        <div>
            <ul class="social-networks">
                <li>
                    <a href="http://facebook.com" target="_blank" rel="noopener"
                        aria-label="Visit out Facebook page (opens in a new tab)"><i
                            class="fa-brands fa-facebook"></i></a>
                </li>
                <li>
                    <a href="http://instagram.com" target="_blank" rel="noopener"
                        aria-label="Visit out Instagram page (opens in a new tab)"><i
                            class="fa-brands fa-instagram"></i></a>
                </li>
                <li>
                    <a href="http://twitter.com" target="_blank" rel="noopener"
                        aria-label="Visit out Twitter page (opens in a new tab)"><i
                            class="fa-brands fa-twitter"></i></a>
                </li>
                <li>
                    <a href="http://pinterest.com" target="_blank" rel="noopener"
                        aria-label="Visit out Pinterest page (opens in a new tab)"><i
                            class="fa-brands fa-pinterest"></i></a>
                </li>
            </ul>
            <p>&copy; <em id="date"></em> Sina Stiller</p>
        </div>
    </footer>

    <!-- Font Awesome Script -->
    <script src="https://kit.fontawesome.com/3281dfb8c8.js" crossorigin="anonymous"></script>

    <!-- Bootstrap JS CDN-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous">
    </script>

    <script>
        function todayDate() {
            var d = new Date();
            var n = d.getFullYear() + "  ";
            return document.getElementById("date").innerHTML = n;
        };

        todayDate()

        setTimeout(function () {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
</body>

</html>

templates/booking.html
{% extends 'base.html' %}
{% block title %} Happy Leeks | Book your Table {% endblock %}

{% block content %}
<div class="container card card-body mt-5 mb-5 mx-auto booking">
    <form action="{% url 'booking:table_booking' %}" method="POST">
        {{ form.non_field_errors }}
        {% csrf_token %}

        <div class="row guest justify-content-center">

            <div class="col-md-6 mt-4 mb-4">
                <h1 class="text-center">Make a reservation:</h1>
                <h5 class="text-center">Select number of guests:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.number_of_guests.errors }}
                        {{ form.number_of_guests }}
                    </div>
                </div>
                <p class="text-center mt-3">For a booking for more than 4 people please call the restaurant.</p>
            </div>

        </div>
        <div class="row name-phone justify-content-center">
            <div class="col-md-6 mb-4">
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.name.errors }}
                        <p>Name:</p>
                        {{ form.name }}
                    </div>
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.phone.errors }}
                        <p>Phone Number:</p>
                        {{ form.phone }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row date justify-content-center">
            <div class="col-md-6 mt-4 mb-4">
                <h5 class="text-center">Please select a date:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.date.errors }}
                        {{ form.date }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row time justify-content-center">
            <div class="col-md-6 mt-4 mb-4">
                <h5 class="text-center">Please select a time:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.time.errors }}
                        {{ form.time }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-12 text-center m-1">
                <button class="btn btn-secondary btn-sm justify-content-center" type="submit">Make Reservation</button>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

templates/edit_booking.html
{% extends 'base.html' %}
{% block title %} Happy Leeks | Manage your table booking {% endblock %}

{% block content %}
<div class="container card card-body mt-5 mb-5 mx-auto booking">
    <form method="POST">
        {{ form.non_field_errors }}
        {% csrf_token %}

        <div class="row guest justify-content-center">

            <div class="col-md-6 mt-4 mb-4">
                <h1 class="text-center">Manage your Table Booking:</h1>
                <h5 class="text-center">Select number of guests:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.number_of_guests.errors }}
                        {{ form.number_of_guests }}
                    </div>
                </div>
                <p class="text-center mt-3">For a booking for more than 4 people please call the restaurant.</p>
            </div>
        </div>
        <div class="row name-phone justify-content-center">
            <div class="col-md-6 mb-4">
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.name.errors }}
                        <p>Name:</p>
                        {{ form.name }}
                    </div>
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.phone.errors }}
                        <p>Phone Number:</p>
                        {{ form.phone }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row date justify-content-center">
            <div class="col-md-6 mt-4 mb-4">
                <h5 class="text-center">Please select a date:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.date.errors }}
                        {{ form.date }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row time justify-content-center">
            <div class="col-md-6 mt-4 mb-4">
                <h5 class="text-center">Please select a time:</h5>
                <div class="row justify-content-around mx-5">
                    <div class="col-lg-5 col-md-12 text-center m-1">
                        {{ form.time.errors }}
                        {{ form.time }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-12 text-center m-1">
                <button class="btn btn-secondary btn-sm justify-content-center" type="button" value="UPDATE"
                    data-bs-toggle="modal" data-bs-target="#editMessage">Update Reservation</button>
            </div>
        </div>
        <div class="modal fade" id="editMessage" tabindex="-1" aria-labelledby="editMessageLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editMessageLabel">Reservation Update Request</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to update your reservation?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="mt-2 mb-3 btn btn-secondary" data-bs-dismiss="modal">CLOSE</button>
                        <button type="submit" class="mt-2 mb-3 btn btn-secondary">UPDATE</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- About section-->
<div class="container-fluid px-2 py-3" id="about">
    <div class="container overflow-hidden text-center">
        <div class="row gx-5">
            <div class="col-lg-6 col-md-12 align-self-center border border-end-0 border-5">
                <div class="p-3">
                    <h2 class="intro-about-section">Happy Leeks is a beloved vegan cafe that goes beyond serving
                        delicious
                        plant-based food!</h2>
                    <hr class="border border-dark border-2 ">
                    <p class="about-section">We are committed to creating a nurturing space where people can connect,
                        explore sustainable
                        living, and indulge in mouthwatering dishes. Our menu features a diverse range of flavorful,
                        cruelty-free options that cater to all dietary preferences. We source locally and prioritize
                        eco-friendly practices to minimize our environmental footprint. At Happy Leeks, we believe in
                        the
                        power of food to create positive change in the world. Join us as we redefine vegan cuisine and
                        spread
                        happiness one leek at a time!
                    </p>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 align-self-center">
                <div class="p-3">
                    <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260206/daan-evers-tKN1WXrzQ3s-unsplash_w69y3q_c3iybn.webp"
                        class="img-fluid rounded cafe-inside" alt="inside of cafe">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About section-->

<!-- Photos of Food and Restaurant-->
<div class="container px-2 py-3 mx-auto" id="gallery">
    <div class="col-12">
        <h1 class="text-center mb-3">Our Vibes!</h1>
    </div>
    <div class="row col-lg-12 col-md-12 justify-content-center">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260400/anna-pelzer-IGfIGP5ONV0-unsplash_1_kcn1fn.webp"
            alt="salad bowl">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260400/toa-heftiba-6bKpHAun4d8-unsplash_1_kgxrdr.webp"
            alt="busy cafe environment">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260206/bakd-raw-by-karolin-baitinger-3U7Emni2h4k-unsplash-_1__j0jmai.webp"
            alt="avocado on toast">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260206/nathan-dumlao-6VhPY27jdps-unsplash-_1__ctctcp.webp"
            alt="three cups of coffee">
    </div>
    <div class="row col-lg-12 col-md-12 justify-content-center">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260400/alexandra-tran-Geqztdi_kTY-unsplash_1_rp4xoh.webp"
            alt="acai bowl">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260207/serghei-savchiuc-zR0FXZ0HJKU-unsplash-_1__aafrlz.webp"
            alt="raw blueberry cheesecake">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260206/lefteris-kallergis-_TLKIVSW6Do-unsplash-_1__snz6ej.webp"
            alt="breakfast bap">
        <img src="https://res.cloudinary.com/dwztcnhyh/image/upload/v1689260206/robert-bye-4UGlx_OXqgs-unsplash-_1__a1ose1.webp"
            alt="restaurant atmosphere">
    </div>
</div>

<!-- Photos of Food and Restaurant -->


<!-- Essential information -->
<div class="container-fluid px-2 py-3" id="info">
    <div class="container overflow-hidden">
        <div class="row gx-5">
            <div class="col-lg-7 col-md-12 align-self-center">
                <!-- Map goes here -->
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37017.765036237164!2d-6.304438352041997!3d53.3539206444324!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x486711faed4864bf%3A0x300c7acf18002c0!2sDublin%20City%2C%20Co.%20Dublin!5e0!3m2!1sen!2sie!4v1688116703256!5m2!1sen!2sie"
                    width="500" height="300" style="border:2px solid;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="col-lg-5 col-md-12 align-self-center" id="get-in-touch">
                <div class="p-3">
                    <div class="p-3">
                        <h4 class="text-center">Get in Touch!</h4>
                        <hr class="border border-dark border-2">
                        <h5 class="text-center">Opening Hours <i class="fa-regular fa-clock"></i></h5>
                        <div class="row">
                            <div class="col-6">
                                <p>Monday</p>
                                <p>Tuesday</p>
                                <p>Wednesday</p>
                                <p>Thursday</p>
                                <p>Friday</p>
                                <p>Saturday</p>
                                <p>Sunday</p>
                            </div>
                            <div class="col-6">
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                                <p>08:00 - 16:00</p>
                            </div>
                        </div>
                        <h5 class="text-center">Find Us <i class="fa-solid fa-location-dot"></i></h5>
                        <p>123 Greenwood Avenue</p>
                        <p>Dublin 25</p>
                        <p>County Larkspur</p>
                        <p>IRELAND</p>
                        <h5 class="text-center">Contact Us</h5>
                        <p><i class="fa-solid fa-phone"></i> +353 85 123 4567</p>
                        <p><i class="fa-regular fa-envelope"></i> happyleeks@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Essential Information -->
{% endblock content %}

templates/manage_booking.html
{% extends 'base.html' %}
<title>{% block title %} Happy Leeks | Manage Bookings {% endblock %}</title>

{% block content %}
<div class="row row-cols-1 row-cols-md-2 m-3 g-4">
  {% for booking in bookings %}
  <div class="col-md-4 offset-md-4 col-sm-6 offset-sm-3">
    <div class="card manage border border-0 d-flex justify-content-center h-100 mx-2">
      <div class="card-body h-100 mx-2">
        <h4 class="text-center">
          Name of booking: {{ booking.name }}
        </h4>
        <div class="card-text">
          <div class="align-self-center">
            <p class="mb-1"><strong>Date & Time:</strong> {{ booking.date }} {{ booking.time }}</p>
            <p class="mb-3"><strong>Number of Guests:</strong> {{ booking.number_of_guests }}</p>
          </div>
          <a href="{% url 'booking:edit_booking' booking.id %}" class="btn btn-success">Edit</a>
          <a href="{% url 'booking:delete_booking' booking.id %}" class="btn btn-danger" data-bs-toggle="modal"
            data-bs-target="#deleteMessage">Delete</a>
          <div class="modal fade" id="deleteMessage" tabindex="-1" aria-labelledby="deleteMessageLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteMessageLabel">Confirm Delete Request</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  Are you sure you want to delete your reservation?
                </div>
                <div class="modal-footer">
                  <button type="button" class="mt-2 mb-3 btn btn-secondary" data-bs-dismiss="modal">CLOSE</button>
                  <a class="mt-2 mb-3 btn btn-secondary" href="{% url 'booking:delete_booking' booking.id %}">DELETE</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}